pref('extensions.lmnpop.xpath', '//embed | //object[@data]');
pref('extensions.lmnpop.format', '{tagName} {title} {src|data}');
pref('extensions.lmnpop.blink.style', '2px red dotted');
pref('extensions.lmnpop.blink.speed', 200);
pref('extensions.lmnpop.asvideosize', false);
pref('extensions.lmnpop.allowmove', false);
pref('extensions.lmnpop.singleton', false);
pref('extensions.lmnpop.ontop', false);
pref('extensions.lmnpop.clone', false);
pref('extensions.lmnpop.close', false);
pref('extensions.lmnpop.menuicons', true);
pref('extensions.lmnpop.contextmenu', false);
pref('extensions.lmnpop.contextmenuitem', true);
pref('extensions.lmnpop.videobutton', true);
pref('extensions.lmnpop.toolboxcolorused', true);
pref('extensions.lmnpop.toolboxcolor', '#BEBEBE');
pref('extensions.lmnpop.winlite', false);
pref('extensions.lmnpop.savehistory', true);
pref('extensions.lmnpop.historynum', 10);
pref('extensions.lmnpop.nonresizable', '.mtime.com,v.ifeng.com,v.pptv.com,www.bilibili.tv,www.acfun.tv');
pref('extensions.lmnpop.loadpagelist', '.cntv.cn,v.ifeng.com/live/,www.bilibili.tv,www.acfun.tv');
pref('extensions.lmnpop.lmnidlist', 'v.youku.com#movie_player,www.tudou.com#playerObject,v.ku6.com/film/#video_player,v.ku6.com#ku6player,.iqiyi.com#flash,.qiyi.com#flash,.joy.cn#myplayer,www.56.com#embed_flash_player,www.yinyuetai.com#yinyuetaiplayer,tv.sohu.com#sohuplayer,www.youtube.com#movie_player,www.letv.com#fla_box,v.qq.com#mod_player,video.sina.com.cn/m/#main_flash,v.pptv.com/show/#playbox');